name: Build & Push Container
on:
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      DH_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      REPO: ${{ secrets.DOCKERHUB_REPO }}
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
          username: $DH_USER
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the container
      run: |
        docker build -f Dockerfile \
          -t $DH_USER/$DH_REPO:latest \
          -t $DH_USER/$REPO:${{ github.sha }} \
          .
    - name: Push the container images
      run: |
        docker push $DH_USER/$REPO --all-tags