name: Run Ansible
on:
  workflow_dispatch:

jobs:
  run-playbooks:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python 3
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Upgrade Pip & Install Ansible
      run: |
        python -m pip install --upgrade pip
        python -m pip install ansible
    - name: Implement the Private SSH Key
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - name: Create an Ansible Inventory File for our remote host
      run: |
        mkdir -p ./devops/ansible/
        cat <<EOF > ./devops/ansible/inventory.ini
        [my-host-group]
        ${{ secrets.AKAMAI_INSTANCE_IP_ADDRESS }}
        EOF
    - name: Create a Ansible Default Configuration File
      run: |
        mkdir -p ./devops/ansible/
        cat <<EOF > ./devops/ansible/ansible.cfg
        [defaults]
        ansible_python_interpreter = '/usr/bin/python3'
        remote_user = root
        private_key_file = ~/.ssh/id_rsa
        inventory = ./inventory.ini
        host_key_checking = False
        EOF
    - name: Ping Ansible Hosts
      run: |
       cd ./devops/ansible/ && ansible all -m ping